dist: trusty
sudo: false

language: node_js
node_js:
  - v8
  - v10

cache:
  directories:
  - "$HOME/.npm"

env:
- DEBUG=tape-spawn SHARP_IGNORE_GLOBAL_LIBVIPS=1

matrix:
  allow_failures:
    - node_js: v10

before_install:
- npm i -g npm@latest

install:
- npm ci
- npm run install:all

after_success:
- make build-html
- make build-odt
- make build-docbook

before_deploy:
- git-lfs pull

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: dist
    on:
      branch: master
      node_js: v8
  - provider: releases
    prerelease: true
    skip-cleanup: true
    api-key: "$GH_TOKEN"
    file-glob: true
    file: dist/book.*
    on:
      tags: true
  - provider: npm
    skip-cleanup: true
    on:
      tags: true
    email: "hi@oncletom.io"
    api-key: "$NPM_TOKEN"
