language: node_js
node_js: v4
sudo: false

cache:
  directories:
  - node_modules

install: make install

script:
- npm test
- make clean build

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ]; then make deploy-html; fi

env:
  global:
  - secure: cO4bDza/9iSsUGVPTJzbl5vXxrr6e0oFgLngqrQcXGcqfJcEvkpKh0xC2Q8d67KixtKnb3TEqOIw/WIKVmTkAVSpLWxtuIu/SNaMQIAbjcNqLhzMeP/s8q5CqeOgAUbVjJB/WKwcr4ZwU4c2ndnwMqU96Sa5RZrBj8vmbFLdMH4=
