dist: trusty
sudo: false

language: node_js
node_js: v6

cache:
  directories:
  - node_modules

before_install:
- mkdir -p /tmp/git-lfs
- curl -L https://github.com/git-lfs/git-lfs/releases/download/v2.0.0/git-lfs-linux-amd64-2.0.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1

before_deploy:
- /tmp/git-lfs/git-lfs pull
- make clean build-html

deploy:
  - provider: script
    script: make deploy-html
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "GL2RVpkQ48gRmQxjXH1mD4w+pUiKkwO9NshqD2tStLMtHBcQwI5HxXsNzZw6kut2N7BGm0U5V67X4EJLMQqlp/MdOHHJyv5YwMmvZae1fKzHThA4j3PT7dx5Z35Jpv9QSrPKAv3qKiNhPDzWjiVCNeHKlsu2AIR1ECrK4RF/h7c="

env:
  global:
  - secure: cO4bDza/9iSsUGVPTJzbl5vXxrr6e0oFgLngqrQcXGcqfJcEvkpKh0xC2Q8d67KixtKnb3TEqOIw/WIKVmTkAVSpLWxtuIu/SNaMQIAbjcNqLhzMeP/s8q5CqeOgAUbVjJB/WKwcr4ZwU4c2ndnwMqU96Sa5RZrBj8vmbFLdMH4=
