dist: trusty
sudo: false

language: node_js
node_js: v6

cache:
  directories:
  - node_modules

services:
- docker

before_install:
- git lfs install
- git lfs pull

before_deploy:
- make clean install build-html

deploy:
  provider: script
  script: make deploy-html
  skip_cleanup: true
  on:
    branch: master

env:
  global:
  - secure: cO4bDza/9iSsUGVPTJzbl5vXxrr6e0oFgLngqrQcXGcqfJcEvkpKh0xC2Q8d67KixtKnb3TEqOIw/WIKVmTkAVSpLWxtuIu/SNaMQIAbjcNqLhzMeP/s8q5CqeOgAUbVjJB/WKwcr4ZwU4c2ndnwMqU96Sa5RZrBj8vmbFLdMH4=
