image: Visual Studio 2017

environment:
  matrix:
  - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
  - npm install
  - npm run install:all

build: off

cache:
  - '%AppData%/npm-cache'

test_script:
  - node --version
  - npm --version
  - npm test
