image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: '14'
      PLATFORM:       'x64'
      npm_version:    '6'
      DEBUG:          'tape-spawn'
      SHARP_IGNORE_GLOBAL_LIBVIPS: '1'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
  - npm config set prefer-offline true
  - npm install
  - npm run install:all

build: off

cache:
  - '%AppData%/npm-cache'

test_script:
  - node --version
  - npm --version
  - npm test
